// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'H:/source/ant-design-pro/node_modules/.pnpm/@umijs+renderer-react@4.0.69_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type {  History } from 'H:/source/ant-design-pro/node_modules/.pnpm/@umijs+renderer-react@4.0.69_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'H:/source/ant-design-pro/node_modules/.pnpm/umi@4.0.69_@babel+core@7.22.1_@types+node@20.2.5_@types+react@18.2.7_eslint@8.35.0_jest@29.5._r6ayhsmuau5tfim7cazeixhtne/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'H:/source/ant-design-pro/src/.umi/plugin-access';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from 'H:/source/ant-design-pro/src/.umi/plugin-locale';
export { Provider, useModel } from 'H:/source/ant-design-pro/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'H:/source/ant-design-pro/src/.umi/plugin-request';
// plugins types.d.ts
export * from 'H:/source/ant-design-pro/src/.umi/plugin-access/types.d';
export * from 'H:/source/ant-design-pro/src/.umi/plugin-antd/types.d';
export * from 'H:/source/ant-design-pro/src/.umi/plugin-layout/types.d';
export * from 'H:/source/ant-design-pro/src/.umi/plugin-request/types.d';
